### ISSUE TITLE
Client.php typo

### ISSUE THREAD

**Issue by traumst** [unstable-cacao/UnixSocks#1]
I think there are a few places with the same typo in **Client.php**
See the screenshot below:
![typo](https://user-images.githubusercontent.com/28272074/44945674-533f8800-adf7-11e8-81fd-c6ad1fb0dcfe.png)

It seems that the proper assignment be:
`$stopPosition = is_null($stopPosition) ? $position : min($**stopPosition**, $position);`

**Comment by ceres66** [comment]
Fixed in 1.0.1
